config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#index'
  resources :restaurants, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get :chef_name
    end
    collection do
      get :top
    end
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @restaurants = policy_scope(Restaurant)
  end
  def show
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end
  def chef_name
    @restaurant = Restaurant.find(params[:id])
  end
  def top
    @restaurants = Restaurant.where(stars: 5)
    authorize @restaurant
  end
  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
    authorize @restaurant
  end
  def edit
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end
  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    authorize @restaurant
    redirect_to @restaurant
  end
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
    authorize @restaurant
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :chef_name, :stars)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to @review.restaurant
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestMe2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/chef_name.html.erb
<h1>PAGE DU CHEF</h1>
<%= @restaurant.chef_name %>
<%= link_to "retour", @restaurant %>

app/views/restaurants/edit.html.erb
<h1>FORMULAIRE DE MODIF</h1>
<%= render "shared/form" %>
<%= link_to "retour", @restaurant %>

app/views/restaurants/index.html.erb
<h1>ALL RESTAURANTS</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
  <li>
    <%= restaurant.name %>
    <%= restaurant.user_id %>
    <%= link_to "show", restaurant %>
    <% if policy(restaurant).edit? %>
      <%= link_to "edit", edit_restaurant_path(restaurant) %>
    <% end %>
    <% if policy(restaurant).destroy? %>
      <%= link_to "delete", restaurant, method: :delete, data: { confirm: "are you sure?"} %>
    <% end %>
  </li>
  <% end %>
</ul>

<%= link_to "Creer un resto", new_restaurant_path %>
<br>
<%= link_to "ALLER BEST RESTO", top_restaurants_path %>

app/views/restaurants/new.html.erb
<h1>FORMULAIRE DE CREATION</h1>
<%= render "shared/form" %>
<%= link_to "retour", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.stars %></p>
<p><%= link_to "chef page", chef_name_restaurant_path(@restaurant) %></p>
<%= link_to "modifier resto", edit_restaurant_path(@restaurant) %>
<br>
<%= link_to "supprimer resto", restaurant_path, method: :delete, data: { confirm: "are you sure?"} %>
<br>
<%= link_to "laisser un comm", new_restaurant_review_path(@restaurant) %>
<br>
<ul>
  <% @restaurant.reviews.each do |review| %>
  <li>
    <%= review.content %>
    <%= link_to "delete", review, method: :delete, data: { confirm: "are you sure?"} %>
  </li>
  <% end %>
</ul>
<br>
<% if  @restaurant.stars == 5 %>
  <%= link_to "retour", top_restaurants_path %>
<% else %>
  <%= link_to "retour", restaurants_path %>
<% end %>

app/views/restaurants/top.html.erb
<%= link_to "HOME PAGE", root_path %>
<h1>BEST RESTAURANTS</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li>
    <%= restaurant.name %>
    <%= link_to "show", restaurant %>
  </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>FORMULAIRE DE REVIEW</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.submit "envoyer" %>
<% end %>

app/views/shared/_form.html.erb
<%= form_for (@restaurant) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :chef_name %>
<%= f.text_field :chef_name %>
<%= f.label :stars %>
<%= f.number_field :stars %>
<%= f.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <%= current_user.nickname %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>